---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: theme-park
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/onedr0p/theme-park
      tag: 1.13.6@sha256:437b79c45c1eb8f3af933ade4d094e2320a0db44737e5f053534f889d5a7cb5e

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.hsn.dev
        hosts:
          - host: &host "theme-park.hsn.dev"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 64M