apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-server
  namespace: default
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest@sha256:0bced47fffa3361afa981854fcabcd4577cd43cebbb808cea2b1f33a3dd7f508
      command: ["/bin/bash", "-c", "while true; do sleep 10; done"]
      resources:
        requests:
          cpu: 323m
          memory: 443M
        limits:
          memory: 886M
