---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-database-mariadb-photoprism
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/database/mariadb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: mariadb-photoprism
      namespace: database
  interval: 30m
  retryInterval: 1m
  timeout: 3m
