---
- name: "Autoscan : Config folder"
  ansible.builtin.file:
    path: "{{ apps.autoscan.data_folder }}"
    state: directory
    mode: '0755'

- name: "Autoscan : Manage image"
  community.docker.docker_image:
    source: pull
    name: "{{ apps.autoscan.image }}"

- name: "Autoscan : Manage configuration"
  become: true
  ansible.builtin.template:
    src: autoscan/config.yml.j2
    dest: "{{ apps.autoscan.data_folder }}/config.yml"
    mode: 0644
  register: var_autoscan_config

- name: "Autoscan : Manage container"
  community.docker.docker_container:
    name: "autoscan"
    image: "{{ apps.autoscan.image }}"
    state: started
    restart: "{{ var_autoscan_config.changed }}"
    volumes:
      - "{{ apps.autoscan.data_folder }}:/config"
    mounts:
      - source: /volume1
        target: /mnt/volume1
        read_only: true
        type: bind
    env:
      TZ: "America/Chicago"
      PUID: "0"
      PGID: "0"
      AUTOSCAN_VERBOSITY: "1"
    published_ports:
      - 3030:3030