---
- name: "Minio : Fetch secrets from 1Password"
  delegate_to: 1pwconnect.hsn.dev
  onepassword.connect.item_info:
    vault: hsn.dev
    item: Minio
  no_log: true
  register: op_item_minio

- name: "Minio : Data folder"
  ansible.builtin.file:
    path: "{{ apps.minio.data_folder }}"
    state: directory
    mode: '0755'

- name: "Minio : Manage image"
  community.docker.docker_image:
    source: pull
    name: "{{ apps.minio.image }}"

- name: "Minio : Manage container"
  community.docker.docker_container:
    name: "minio"
    image: "{{ apps.minio.image }}"
    state: started
    # restart: "{{ var_minio_config.changed }}"
    volumes:
      - "{{ apps.minio.data_folder }}:/data"
    command:
      - "server"
      - "/data"
      - "--console-address"
      - ":9001"
    env:
      TZ: "America/Chicago"
      MINIO_ROOT_USER: "{{ op_item_minio.op_item.fields.username.value }}"
      MINIO_ROOT_PASSWORD: "{{ op_item_minio.op_item.fields.password.value }}"
    published_ports:
      - 9000:9000
      - 9001:9001