---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: thanos-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET_NAME: thanos
        S3_BUCKET_HOST: s3.hsn.dev
        S3_BUCKET_REGION: us-east-1
        S3_ACCESS_KEY: "{{ .garage_thanos_access_key_id }}"
        S3_SECRET_KEY: "{{ .garage_thanos_secret_key }}"
  dataFrom:
    - extract:
        key: garage
      rewrite:
        - regexp:
            source: "(.*)"
            target: "garage_$1"