apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-server
  namespace: default
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest@sha256:dfd64a3b4296d8c9b62aa3309984f8620b98d87e47492599ee20739e8eb54fbf
    command: ["/bin/bash", "-c", "while true; do sleep 10; done"]
    resources:
      requests:
        cpu: 323m
        memory: 443M
      limits:
        memory: 886M