apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-server
  namespace: default
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "while true; do sleep 10; done"]
