---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unpackerr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/unpackerr
      tag: 0.11.2@sha256:2e11ef1736feecafc092cf8428ed051513a5d1c09cde63af70b697c729f5affb
    env:
      TZ: America/Chicago
      UN_SONARR_0_URL: http://sonarr.downloads.svc.cluster.local:8989
      UN_SONARR_0_PATHS_0: /complete/Series
      UN_RADARR_0_URL: http://radarr.downloads.svc.cluster.local:7878
      UN_RADARR_0_PATHS_0: /complete/Movies
    envFrom:
      - secretRef:
          name: unpackerr-secret
    service:
      main:
        enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [10000]
    persistence:
      complete:
        enabled: true
        type: nfs
        server: nas.jahanson.tech
        path: /volume1/Media/Downloads/Complete
        mountPath: /complete
    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        cpu: 2040m
        memory: 215M
