---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres
  namespace: database
spec:
  teamId: "jahanson"

  volume:
    size: 30Gi

  numberOfInstances: 3

  users:
    postgres: # database owner
      - superuser
      - createdb

  postgresql:
    version: "15"
    parameters:
      max_connections: "300"
  sidecars:
  - name: "exporter"
    image: "wrouesnel/postgres_exporter"
    ports:
      - name: exporter
        containerPort: 9187
        protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 256M
      requests:
        cpu: 100m
        memory: 200M
    env:
      - name: "DATA_SOURCE_URI"
        value: "postgres/postgres?sslmode=disable"
      - name: "DATA_SOURCE_USER"
        valueFrom:
          secretKeyRef:
            name: postgres.postgres.credentials.postgresql.acid.zalan.do
            key: username
      - name: "DATA_SOURCE_PASS"
        valueFrom:
          secretKeyRef:
            name: postgres.postgres.credentials.postgresql.acid.zalan.do
            key: password
  # Restore procedure:
  # - Remove the existing cluster
  # - Uncomment the "clone" section below to restore a point in time backup
  # - Apply the config and let the cluster restore
  # - Uncomment the "clone" section below
  # clone:
  #   cluster: "postgres"  # The source cluster name
  #   timestamp: "2023-03-21T19:50:00+00:00"  # timezone required (offset relative to UTC, see RFC 3339 section 5.6)
  