---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mastodon
  namespace: fediverse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mastodon-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET_NAME: mastodon
        S3_BUCKET_HOST: s3m.hsn.dev
        S3_BUCKET_ENDPOINT: https://s3m.hsn.dev
        S3_BUCKET_REGION: us-east-1
        S3_ACCESS_KEY: "{{ .minio_mastodon_access_key }}"
        S3_SECRET_KEY: "{{ .minio_mastodon_secret_key }}"
        S3_USER: "{{ .minio_username }}"
        S3_USER_SECRET_KEY: "{{ .minio_password }}"
        SMTP_PASSWORD: "{{ .mastodon_smtp_password }}"
        SMTP_USER: "{{ .mastodon_smtp_user }}"
        REDIS_PASSWORD: "{{ .mastodon_redis_password }}"
  dataFrom:
    - extract:
        key: minio-s3m
      rewrite:
        - regexp:
            source: "(.*)"
            target: "minio_$1"
    - secretKey: mastodon_smtp_password
      remoteRef:
        key: mailgun
        property: mastodon_smtp_password
    - secretKey: mastodon_smtp_user
      remoteRef:
        key: mailgun
        property: mastodon_smtp_user
    - secretKey: mastodon_redis_password
      remoteRef:
        key: mastodon
        property: redis_password