---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fediverse
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  # - ./pvc.yaml
  # - ./minio.yaml
  # - ./replicationsource.yaml
commonLabels:
  app.kubernetes.io/name: mastodon
  app.kubernetes.io/instance: mastodon