---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mastodon-system
  namespace: fediverse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
