---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpackerr
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unpackerr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        UN_RADARR_0_API_KEY: "{{ .radarr_api_key }}"
        UN_SONARR_0_API_KEY: "{{ .sonarr_api_key }}"
  data:
    - secretKey: sonarr_api_key
      remoteRef:
        key: sonarr
        property: api_key
    - secretKey: radarr_api_key
      remoteRef:
        key: radarr
        property: api_key