---
kind: Kibana
apiVersion: kibana.k8s.elastic.co/v1
metadata:
  name: mastodon
  namespace: fediverse
spec:
  version: 7.17.9
  count: 1
  elasticsearchRef:
    name: mastodon
  config:
    server.publicBaseUrl: https://kibana.hsn.dev
