---
kind: Kibana
apiVersion: kibana.k8s.elastic.co/v1
metadata:
  name: main
  namespace: elastic
spec:
  version: 7.17.9
  count: 1
  elasticsearchRef:
    name: main
  config:
    server.publicBaseUrl: https://kibana.hsn.dev
