---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: morgoth
  CLUSTER_ID: "1"

  # Gateway IP's
  GATEWAY_MANAGEMENT: 10.1.1.1

  # Networks
  NETWORK_SERVERS_CIDR: 10.1.1.0/24
  NETWORK_K8S_POD_CIDR: 10.244.0.0/16
  NETWORK_K8S_SERVICE_CIDR: 10.96.0.0/12
  NETWORK_BGP_SVC_RANGE: 10.45.0.0/16

  # Loadbalancer IP's
  SVC_INGRESS_ADDR: 10.45.0.1
  SVC_VECTOR_AGGREGATOR_ADDR: 10.45.0.2
  SVC_K8S_GATEWAY_ADDR: 10.45.0.3
