---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: downloads-gateway-vpnconfig
  namespace: vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: downloads-gateway-vpnconfig
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: VPN
        property: pod_gateway_downloads_private_key
    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        key: VPN
        property: pod_gateway_downloads_public_key
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: VPN
        property: pod_gateway_downloads_addresses
    - secretKey: VPN_ENDPOINT_IP
      remoteRef:
        key: VPN
        property: pod_gateway_downloads_endpointip
    - secretKey: VPN_ENDPOINT_PORT
      remoteRef:
        key: VPN
        property: pod_gateway_downloads_endpointport
