---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app minio
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2023-03-24T21-41-23Z
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    service:
      main:
        ports:
          http:
            port: &port-console 9001
          api:
            enabled: true
            port: &port-api 9000
    args:
      - server
      - /data
      - --console-address
      - :9001
    persistence:
      config:
        enabled: true
        type: nfs
        server: "nas.jahanson.tech"
        path: /volume1/s3m
        mountPath: /data/

    podSecurityContext:
      runAsUser: 0
      privileged: true

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.home.arpa/enabled: "true"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-body-size: 100m
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            chunked_transfer_encoding off;
        hosts:
          - host: &host-console "minio-s3m.hsn.dev"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port-console
          - host: &host-api "s3m.hsn.dev"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port-api
        tls:
          - hosts:
              - *host-console
              - *host-api
    envFrom:
      - secretRef:
          name: minio-secret