---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.6.1

    podAnnotations:
      k8s.v1.cni.cncf.io/networks: |
        [{
          "name": "multus-iot",
          "namespace": "network",
          "ips": ["10.1.3.151/24"]
        }]

    envFrom:
      - secretRef:
          name: home-assistant-secret

    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "10.45.0.5"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.hsn.dev
        hosts:
          - host: &host "istari.hsn.dev"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    resources:
      requests:
        cpu: 126m
        memory: 8Gi
      limits:
        memory: 16Gi

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
