apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: security
stringData:
    onepassword-credentials.json: ENC[AES256_GCM,data:2GFD/KIFWZH5iH+h4/6crBUNJQdLYRnWvW8zR7XWopQ1OabPBtKYXo3HVna/D6rYVKRPrZDQcq6eit7Z6Iki7BYFSxR4sJu5n5meNbdZcx0Z7q4v5uKXPowegzMm7J+BZnGhOWP49vAh8Ku91L0B3vI1p2pk9MkGwLVh1cel//1pVSQDSKnvDWSzHVsj+HDmXP1BO5cP1hasa/aZURP1WUZ9OjRMHdraSQV0IhR33FSqdr3bYFQyZ+QGjScC29KO+yduxHUgs+KHQQEa4N6Jo6LNTI77Kb36CraBNYDDr0LR161zF3jQI/tSymMA9y01Mlr+EJS87I+owqIiiabAcrewidJdNbhPazSvbrzDtEvVhuHPe8zPPpOI2Xqukq8vt+4i2+uIEifmQitIms9BAokypO6JFdfpH8pg5RUFE2TPft0ayDVE6QngrDLdDZY8sqziBpDOjc4pWTA6T/ktD+wLYaIWorem7MUso5i29h8Ah4OPxhr0DaPL+n74tcTQ44Zg8PzHjh3CBctraV5cpDH67zcveeMjJ9CI3NMjFoQ16GqbDSi4rZQYWh4czJCJxfbWJiEJd9qfxczS3GebqjqJDDAG1TCTRGn1YhqUYGkljXRBWx/pxzdNhYd0PnQYcwf41OkBI6y7D0Y6oDLFsOUvtD3ZMqjYFKf6tmzAMzOeiOsa1XGsBZTcBACwHsRylRcAt/AbKS69HbgLR0OkXMfzb2vw4M+IvQ0UmJEy6uw2wDh3lvqV/TF3PKFUEVdj2AmchEfr50Xz5ZQGxfNeNTAqpVtJCT7U4k1pFIYxRASzEmVGO6OL2V2WGJWSjDSRDgfloJfDWKhv7hO8A3Ez+zeizADwj5e1oFTOX5kaRqdNuawaOW54VCb0twQDq2e4l9OLU0yFYjj6Nd79XMTVKltkGxv0HQnGAiLcH3Ch4rUcAxguAvXawKkcYccsJFEqLDlbfgeIN+ufFlJvUjlzSL9D/8R+7oZX63ZE8g4vfqdciID3XDaTUSOpqXl8jxBgdLZY+EgjaHwyjnnZZirwr69dIwHhCiMuoYxcFxl06QschjR8wAS/3wOTqdHkNyzYdHZE+VtyW/QA209ofwLpnQhtB0ekKSdsXQSNl93GUIML/bCYhcK6IodT/6vPyfZGxXumo60W89R1umYY9OFPMf7Sea7AQjNfV43j9XrGY4dDm88Eb61SkvOX+R8CHONBr+FV6ZTKrz5qjBQqHlZvWpmBg4cpl3YTrFGgWrEOWhDc+L5N8mVgFMGoY8BRvKJanCk6hMcu2fokPPlVsxAjaZ6CZzIUf6rnuWxwXLgzP64N90xpTM8jr8V03jeLvfReVUDD2LxudZyeHPRveikLS+CSvCaeGbBppkwq/ixuE0CBl4+BkeGFhW3OpKVuhcuOWykHu0YAKtsy9grQ1q1pHqvKCQtGGhEwkYrLdIuSnRBH9jAqw/Cbw4fGVgxbuP0RXGcH61gcw0ZJH1AL4bcwclSwhzbF+7K4jgEdShnWKqIuM4rhbrFefT7lChCzwC7hKUs0Ln/0zXuM/HVhJttEV5gGjjF/2oEHWnt5cq8jpDQ5ZOotMgkshBlYhPqc6WhoItM/o208+ZIQY/nak3l8jFIqI22XajTip220DQZotyozjU2aY3fPoERFPxj6UPczLBlBPJPwsivj6pOIjz96PvebYKvtghBbGKWt1DJ+qzcQruOQw8l0BELRUoF4ww3oWgPgEZJwoCyUHF0pKXockQ2Ih+3SD5u91hKI5yvZjpT13jmBorotzn+0eL1aY6+Fwtn0wXMdN7sTrAjsDrlfsKN7eU3DftNkTXN6AJJn6r2295OV1j5pYTqnpHqqHrfaTHKzFBwn9M7d5zV7rM+Qy8W+CoDF0acP2EpDC341TfaXfBNfkQFQNnIs2OFSIJ5HhFoOu5DQl/gZ53Ex,iv:DoLTu4L/WdDpTVwuqlNUir72hcLsyX6KnceQZG/wqUg=,tag:VOfi01MASaMTtTl/e1TVvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qslan3wn5sjtsyc74qt976hm0s0u6zjufnqz822uuwyg08krdaq4vu4yu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNjhPQzZKQkJMQS9TYUxZ
            aXg0QlFOZlBCYUVWY2tkUFlCT3k3L1VXOVNRCkhOM3I0WUdXSjRtS0dtVmJ1QVM0
            bkM1S2VjQllKZy9xbS92VkFhWXdnU2MKLS0tIG90MlJEOUgrQ29ZVVUvUlBFK3Ny
            aDFTRDhyYkhYNVYzeStXeW02U0lpb0UKryeISjBmFkTVukuhFYRsy+dgmAWJ0v2A
            y9cnoghFyKZyfdLAG7hsGIt5bDGakueagmIgoMHgckRRBNbTymXENw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-06T14:28:38Z"
    mac: ENC[AES256_GCM,data:7xlfKri777Zf2aKyRbN3qHLNy5dkBALSDI58xrWWAA3wxCiriwjIiPDui7zJQDZlxhCnSjqzP/ZJF7Nbin+1NQXdm2gOWtiQpSM030izk8q1SSzba+dHKoy0HdcMqvBMXXOEO27p6eg2aLw8lT++4L8xBy9O+J+MQP1XguJ2aNc=,iv:V76vuFwDlYo8F5q4Wfb3S6BmD1IJXkSPgXc98keBpBQ=,tag:HwbGi7cdVgELIAoDmjbVuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:xS/bMUGEG9u0zS2MDI4woQB2TI2pEjACLzq930HU+G2dtTEPHpvPowI5j8RxAqaWGqsTgMUXddWl7VuxtuKC2qhP8Hc2w2++cGmZFWh21DtsCysaGnpFfhh44yoCUIcHhwgiU5f1f/wYALOL/MVfzBJdd3M9aEUCOeI6qA7fLIOo2WDumTOFe4++yWlXIy2vur7Zw/2ZT//DenvY+0bX8B5KvpXOlYd/fWTn276QGEAJ7AIjmcHhGboydFx5V58sQWpgviHUhPCB8sxJ6hG/qQ8jioEmhxkZV9r9PQjqFbLrces9XPyxq6Ij6rVG5tLXVju1ZwKKkq+gqX1C2yOEf6p23V+nYWeJbNs3/eBhvL9ZGYK8OA0wuXBEH8dKNN/CmyanyzdK57wkDLMISnIWmbORMHjxM/3VzjEe+DJCq58zzfJwe56ohLH9gJIjDBRPU58OlVMUx8BMb00uYGNlrWaAZIUt4Pqsh61VAIg8S3LkS/IAcL6UHcSZMFxRfpeFXTqFMR4Jegs7qb0LDjkQEtUsLuySbFUJqCI/o0NLFo55e9Az8Krkmw/pB1XEFjPindUtIsSgH9sRxOqJ1v1waihc3t+7+d6mIbb3i59i/5erSpKrFCTJTbkjKxYZ5EcIL+DVJ8SvzwWSZNX8SbHB4BWwFFpQf2G4Iwke18oJjaa9YqT/OVezXRTQ8IsZcMAdP6SB4nfJv32H2qbmh25P5WU2Q7xMoPJseqLU4F0U7Vstw/wSiVoA0v/HLXW5hpKXEh5gM68chuOVsXP8vaoFuT79y+yczsBokak6lmZU8hOiaG+ZU8ePHeB/H2z6Uuu7bqvAbtCKoCr64nQTqxYIZ9avhUdVJMDSNFFzBX/pmxrx4lf0snRfrzSuQCcQcqh3Ym7sUCv/wuUGPBALr2jJpjCuC7v3TADC5Ww=,iv:4C34UnZ4cnYe89IUNy9lJBk6MXB90I+pzOUwNl8OQhM=,tag:PVBP6WA7k9ZGCJSWstSBdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qslan3wn5sjtsyc74qt976hm0s0u6zjufnqz822uuwyg08krdaq4vu4yu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNjhPQzZKQkJMQS9TYUxZ
            aXg0QlFOZlBCYUVWY2tkUFlCT3k3L1VXOVNRCkhOM3I0WUdXSjRtS0dtVmJ1QVM0
            bkM1S2VjQllKZy9xbS92VkFhWXdnU2MKLS0tIG90MlJEOUgrQ29ZVVUvUlBFK3Ny
            aDFTRDhyYkhYNVYzeStXeW02U0lpb0UKryeISjBmFkTVukuhFYRsy+dgmAWJ0v2A
            y9cnoghFyKZyfdLAG7hsGIt5bDGakueagmIgoMHgckRRBNbTymXENw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-06T14:28:38Z"
    mac: ENC[AES256_GCM,data:7xlfKri777Zf2aKyRbN3qHLNy5dkBALSDI58xrWWAA3wxCiriwjIiPDui7zJQDZlxhCnSjqzP/ZJF7Nbin+1NQXdm2gOWtiQpSM030izk8q1SSzba+dHKoy0HdcMqvBMXXOEO27p6eg2aLw8lT++4L8xBy9O+J+MQP1XguJ2aNc=,iv:V76vuFwDlYo8F5q4Wfb3S6BmD1IJXkSPgXc98keBpBQ=,tag:HwbGi7cdVgELIAoDmjbVuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
