apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: security
stringData:
    onepassword-credentials.json: ENC[AES256_GCM,data:yjzkIpkoDV1sKUZVolBppjaInCkzwAYZPhMtHsrbnE8cmBmi9XEgeiI31e+cF6lLnTUqjqRubvaRqqmsOSqaFEAxGRKAKydITZ+sPXWxsXg+Eu+rV/spC69uQBZwvmNUQlmJPcW/i2ybJzm5rk5f5mgic7x36uIQkAblY3tjkVCh9Ncrb42Kl1J6Cf9NerXx/jaczl5xli9SiZDTU9j2UXeWu/tbYjxnCY5sheeN1aIkELh6kyIsU/w/G+guB/I8ND+cCKyzFWWUhnvXsGY2yKGPXgsniQZTcoWEOtV7mB3Uy7gNeoXRvj1Qh3FaCQgS2KOzr8LdznVphVQ/fuo+9G+EluBMRExl0RJ6pAjNGmSIGSi89UAadnrKxKUQCvbbPaek/Va/Ps/9F2PMp2PlIrRVK1qxo9D2Pp0WwRUE0jEHGPNefNxyoK8dJ23BMmsCcqNmHXmmFh7ylajOcAN1ODYrtWGQz1eCm+ott2BXmc1mc4hReV0wQBtcgaOzGFnaOP1l+yRWpIigAkur5wp55sXip3OOd0mLmFIFl+MUxMnK6xP/qZ8VR6+6sjED+avV1GPR8SYowBI+s+S953IPTXNsKucWb2kHFdIRMzO+3ViaiDR2it6rcukD9FnFlBX7Kj5WfzL8POa8H5oFoU/UDCubSuwvXu2FCvDrMcW/esHGyuad+sgn4+3QonnZHeyl/DU53sXFr9hQUbEIndY14QKxk+/N/pXdHcOsuVtKaSAokY8dWln6KxJEI+PQFs1YZ1xcGW7//V6KeuPxK8om6HXC6/HWrtQlkXfeMr6SaSWE4oujF8vH9XjvIAiBfIBhBBjtIZ23Rk8yNGpBjoz5SGoGJbfhxPQj2ciRL0yZdOVSJ8k2a8pW3i35Ryfu1MTBmZLVvldSo1MOnpV5JMQK2NqTOfuZYFv02KHZhhz/Clce0UHVrMQ1zzN5NdfhWcdJXdQnan5MUSMtYb76pn82PiGBp3GPr2FLMj0SX1ncXsptqoqMkGhu1nT5debU60Y6h8yCEwwI4J+kgtWNlDtYhD9VUQndegMaR0sh5Upqm9HgQqjgsSav2/lkT6Pul5gyedeFVwQJRoCw9qi1FWtgPBel6slrntld+HX9sMrERKNZrVgg7LSJzP+HNA6WpphDKrwUvRTGVgyf3AIVQyqHb0mtGe7PNmMiwE03ZxZMxJgrBFYyR0Wamn36fK6yD5IRQLuGGzNfoRB+k74ttq9Jv/rTGPysiOQhJVefAShqlT9ohLUqc+rMuxdsAm9W0WGvg3KpDc7HwkRQDRVNorv/cWgLTLknKKDotJ9A8nsUXMeb64pBtB8Mq2BS1xFu0WT0XvmfxbSZj8HsoErUmRU0085ZblBAqxwdFXtW4VLVrf3GuOAMWy4nfSOhGWqiNHRiwkFZQ+eHkAPocg/10fHo6pU0EFxztdpYxh3XzJmncZLrxgAlG7KXMiMM1rFqFdRB09gHGej4xTWLy/9ufDH1MEKghlV2Eis1Ha1PkbG2+RhBdgU6XkH5QV0vh15jfvXH8ZAtSRUyUOM6N6RyplkmRwDXJ2JnFU/eqU5rfOQP8C4K/pComujwgfsOTjPC/DFw+M61kIv+SKdZZR+OzVHW/ehf118wKNdtgLr45+dPm1QTPcL2iU/dekS+HGILqayZwWf1RAvfJum1vwXy5RinfJOXHGxXbES1ZL4F6k34SiZjcouljruvvWahqQ3d9rA0buGLvM26pth8RtcPYr31RsXafLah/Ims95L/2ZG2JNGu9WB8UxagGb7ic8nn3sdnAIGBlMuKTQN8ZPUNFe8YiFb/zso77qT2wqGZSp9tcZqclGMtc6Zy67DQ0vi/Hk78XJiX7uCVUYnfS+SQHH1uPoW7qHveOcT1UJmHXaS00mG3gmESZv64jUdC2Jcc+ZgQiTZcZjUdISE5fKrH,iv:Ctc12sl631iS0UxNc0NDuFIZkc4yl0F925LgM5nCWow=,tag:eI5mJQGDAhO/K6ceBFv+vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qslan3wn5sjtsyc74qt976hm0s0u6zjufnqz822uuwyg08krdaq4vu4yu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZkNSRHU2WDFBN3ZFR01j
            cXEyNmJOUGk5SDNwZ3VHa1gvc1dLMTdCNURzCkhORU9qM0o1T25NYXpCL243UW1H
            VXRiOFk1TEJuM3ZVZG5tWi9UR2NVVVEKLS0tIFY5S1VJSllTTVNOUnJFOTlPdW5T
            YzBCQmlKVzZ3K3g1MXp2RTRyQlR3VlUKxZRhUIGVFK0c5qH30kDHPLK1uOz83lF+
            FIUtXMDvZ94PjHjMdYyhAT2aAhZv3QhZaacklju6MYqInSBDK6GthA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-06T14:53:16Z"
    mac: ENC[AES256_GCM,data:NuhRSrBkUe8J7haaCtW29NYZmBI5sWGE3LBCRXakI+Hr1VPOF6HLpDGOBQ/OGp/o7zyPQtm1CbLnP9+nCm95SH0WU83A8c9ViUWhKWScultrhp+m3OwtopOBfz1p0MrUVU2dkinWZ921rNQDnTynuAhKev0Z6613Iwy2EotolCc=,iv:G4Z4zp94yYb4Ec4g1cmKnS6FDqAJakva1voj3KP6RY8=,tag:yFLFk3C8cLExHPBkXIwpRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:DiKO5HZvZhHDu1WNUiDfF1JIiwX7y/uZHLkKnKSIvmO4qUez5WqGh561Xfhbk8ytjIboulbjjMq2w8vhICUd4G3dcA6yWFPHhPaeTPy295f4qyoqGfQsecTRTR3ioO0jbaYLGtl15H90dobDwB9YphZ2CdchFzjh3eF5qEsVmoafnMLCdRsTpBBxBUFr38DpfBBwi3+CdCE7aF3mcUiw2qk0skh2gWWmBN+2VPbH3dpZWBBuxOSF7A8hgw1WB1cqsrd5hrPXgToD07JMqe8O9qLRpGRMQNO8RaDOBykaVnfmrDe7K2AYVL4cJhVQHkaYZSp8tfsTwMbX1I2UPpOrMWt6WMALqcs+WiAILq9njL53Zr+R/coK7Ja/8rlqp5SB0s+eWTgmlzqThkxQFNOpdP/ak0svdRmP9lomIVWVOxdM1uIgimHihXqJzlE/kQUR50EV0YqcMQJvUvZRehGjNnYUxIzakaN0eq0Yf7urg/iH9qUtDJSThjr0tEVfUVNDgNbzsRnbH60UuXNwbjrPQUubs1onhckFQe40147WzFuZGCvVQfxM2VlPKNtzxLYxw8gX9/HpwMiHJA0eIl22dD2nAZvIoRllo7LaxBqA3gEQ2kLqXdeTlX2y0fviyoannDU3UgsDw8pvi94SLmzzfV1H2RjcffBBf2fCVqgk3TRrOqvzhkFnN6kQT34hCRFK0Y2OrDLMBGctpSch+TPRwkxOpIm+adjWVsaDjqWADNRv6ugdIJMb1kujFovoUVtXxUJjfIxJnCrFSXahLHo7gAsS79pX4c2F2v/zkRnE8GQqdcscUkFKQbCjGMBIlwVd+sCiDCgBOGlN3ixC24b9y62WiLlgAuPcbleUKOKVAcMarwVxm1tzcrhOgOPZeRRfqvivSzrCq4kIqbDzSL+eyEpL7cR1a6kU1bZPncwrOFAWBkZIu98jfnH57wWz2GFJGO6rM+N3AuC9E4zA3k5V04F64yH4nF6lMLIIQaomHgEEFo2kHQgCD1iw73jm7CbDceV9XslMFMGJ6/r04HShbMfX/D8UqsDcI7a09rDBjyQOSgB4SdWPCa1tkmwldERljQKntswjQg88wadqoGhcbpTP3AqdSkoJTMZpQufsnXH7hxqjxbCEZtk6ckxZotK0uPbjzz4/r6OzdbbWB7WfrBJT1UXov+hounJed+diYheoxCiWV18MSq9RftTQboqRPCVNi8hDK/2YlwHHmoZk/v0/SSw=,iv:A/Lh+LPxlzhfRat9VVykdSsGEZ/53walrSLeUQoyoAY=,tag:wUD47ZqvPfPr2uyWKU77BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qslan3wn5sjtsyc74qt976hm0s0u6zjufnqz822uuwyg08krdaq4vu4yu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZkNSRHU2WDFBN3ZFR01j
            cXEyNmJOUGk5SDNwZ3VHa1gvc1dLMTdCNURzCkhORU9qM0o1T25NYXpCL243UW1H
            VXRiOFk1TEJuM3ZVZG5tWi9UR2NVVVEKLS0tIFY5S1VJSllTTVNOUnJFOTlPdW5T
            YzBCQmlKVzZ3K3g1MXp2RTRyQlR3VlUKxZRhUIGVFK0c5qH30kDHPLK1uOz83lF+
            FIUtXMDvZ94PjHjMdYyhAT2aAhZv3QhZaacklju6MYqInSBDK6GthA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-06T14:53:16Z"
    mac: ENC[AES256_GCM,data:NuhRSrBkUe8J7haaCtW29NYZmBI5sWGE3LBCRXakI+Hr1VPOF6HLpDGOBQ/OGp/o7zyPQtm1CbLnP9+nCm95SH0WU83A8c9ViUWhKWScultrhp+m3OwtopOBfz1p0MrUVU2dkinWZ921rNQDnTynuAhKev0Z6613Iwy2EotolCc=,iv:G4Z4zp94yYb4Ec4g1cmKnS6FDqAJakva1voj3KP6RY8=,tag:yFLFk3C8cLExHPBkXIwpRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
