apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:nt3ba7UzvYemaMivyU9ikGlEftFjSsC3Ucddxi5aeihfyLc/mcWAMG8GlH+9/1/+PNU/tbDlaZthJQ2+LHJxzhIKsSjCrsE/b2UdwTV0ijQ9b7tgiLTJTmnQXnA3LO34vz+z/ldhGPkeK1RGBP6wTqXKvZzsi5GIEvZyCaLtRGuTcbRoOszBlN6xfJsosMeXOkkGnH9BXdLjVt/u7ukHNmsOmShpQCFi9EXeomHDTyoFtwWDtpXSqElkPKy37kYzdM47qfWRjCPtz3fYPT0CJC2a307ARWR/hWaSHOqLRmAswKilpirNV4TSxTlCCUdQHMtHWq1rKxZa9VxdwXOdkZsolLJQnfHLXlodKMoQNH3lKR4ci5PLOYjjZ+oS5r2toCT/v4U8l6/qI08Z4+cjD7V+XIxhrjtm6d1szZoCdwOXeYX1p7A21S1z/9b+IyyLbOT80kPYpKZ96oYNIyCt3Bm7o4YWhGkDPkd2EXiQHZoTPyPHK8kMFdFfs0hGUGrqqaM7lb4s7nGXAU19C18MkBglAvnb+Rj1NAAb37wUy4K50SUW65xrWYwqtZx+DJSA3AxNBTElnJIv38Aink/xZGuUrDoJMmYdLVl/l3RNwNzvnQRqi+TrtICDvBOlL112uipLT1ss7A5S1zz/ht0QGsXMVvHwhVglasdDfzuWV/YFhwjEZtIlkyTkmJbUslQE4LDTi8h5p2FCvszAPNUwscR/DA9PevpshYfeBM845OsmOrJuIiopRYQl5dyrUDiFzkIqkjg2nc+uaUzH5ee7HDRCdz6q+fYqToPANN8ARR+yhxZ68C9EQ+54S/odjwdRwHFXg3zHnggaAhu3WflC+hX7RCRfUPwV11/kG4p6NpYBRLV6Zf0i1XUphQddkIsPXbPAR5J+wQ/gYG63LM/85b8ksmS1DRy5Gqc=,iv:qZu4eVBGLNshJ39oV1h3MXmEZMr2P8vercEjdGDG5Xw=,tag:sjKVIbIj+1TDt51PC9E4gQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qslan3wn5sjtsyc74qt976hm0s0u6zjufnqz822uuwyg08krdaq4vu4yu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibmZGWUdGUVhvNEZWdnZw
            VDJhWnh6YlNiMFpMK3dhNnVxK3lYcWE2V0hzCjRYbzZodGhXeWZhR1ZKT0pPaGtq
            Uy9UbGlPNkt2RXY1Rk1hN1hoT09ZVFkKLS0tIDRmb3Q3c1BmaTJpY2M4TlZWUTdB
            d2ZvUkg4ZjNYR2U1NmlkeTlveXJ3RmcK8gbC0QH3GZb/8UxpXv8wFB/h/RESZOUT
            nXynoucPQ0dDJInrP8la7wk8b34yb5QeLDxGoTRD0IkmKY/Y1t6aIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-02T18:17:44Z"
    mac: ENC[AES256_GCM,data:wUdJEQgQU+QtgM7CVPKT5TGnnxtBmv9pWEDvscfFZs98w9hQx0rj8LFa+YsVbg+RBXr5kgh402GNNyCCxJ51vhVHRuON8HBEgqtU3RBZUg3G3z+v7iwYoIe+sPrg/YB6L/TUxX5TVDIFZeEfKw471Nu2IgvBZZdDty3i7l2mY2c=,iv:T73Csmn17ywavl9ibligJ7SU0MGJ3cgnBhT0YzbXdvw=,tag:VJvfZvqzTC6vaHH0zwHYAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
