---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.33.0

    env:
      LOG_LEVEL: "info"
      PORT: 80

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.hsn.dev
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.hsn.dev/css/base/overseerr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "overseerr.hsn.dev"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config
        mountPath: /app/config

    resources:
      requests:
        cpu: 15m
        memory: 226M
      limits:
        memory: 1937M
