---
collections:
  - name: community.crypto
    version: 2.12.0
  - name: community.general
    version: 6.6.0
  - name: community.sops
    version: 1.6.1
  - name: community.docker
    version: 3.4.3
  - name: ansible.posix
    version: 1.5.2
  - name: onepassword.connect
    version: 2.2.1

roles:
  - src: geerlingguy.pip
    version: 2.2.0
  - src: geerlingguy.docker
    version: 6.1.0