---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-photoprism
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mariadb-photoprism-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        mariadb-root-password: "{{ .mariadb_root_password }}"
        mariadb-replication-password: "{{ .mariadb_replication_password }}"
        mariadb-password: "{{ .mariadb_password }}"
  dataFrom:
    - extract:
        key: mariadb-photoprism
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mariadb_$1"
