---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mariadb-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MARIADB_ROOT_PASSWORD: "{{ .mariadb_root_password }}"
  dataFrom:
    - extract:
        key: mariadb
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mariadb_$1"
