---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-photoprism
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      chart: mariadb
      version: 12.2.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      database: "photoprism"
      username: "photoprism"
      existingSecret: "mariadb-photoprism-secret"
    primary:
      persistence:
        enabled: true
        existingClaim: mariadb-photoprism
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 22m
        memory: 163M
      limits:
        cpu: 106m
        memory: 755M
