---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-redis
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/database/redis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: redis
      namespace: database
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-redis-lb
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-redis
  path: ./kubernetes/cluster-0/apps/database/redis/lb
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: redis-lb
      namespace: database
  interval: 30m
  retryInterval: 1m
  timeout: 3m