---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elk
  namespace: fediverse
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/elk-zone/elk
      tag: v0.9.2@sha256:bc7951f8f0ddae1c772bee1b8080b6e863c76c9424a3652a3b55bac988c4ebd3

    env:
      NUXT_PUBLIC_DEFAULT_SERVER: "social.hsn.dev"

    podSecurityContext:
      runAsUser: 911
      runAsGroup: 911
      fsGroup: 911
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    service:
      main:
        ports:
          http:
            port: 5314

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.hsn.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        hosts:
          - host: &host "elk.hsn.dev"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: elk-config
        mountPath: /elk/data

    resources:
      requests:
        cpu: 15m
        memory: 164M
      limits:
        memory: 1408M
