---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elk
  namespace: fediverse
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/elk-zone/elk
      tag: v0.8.0@sha256:e0cabcce025dd78b32bd760bf12eb6d3d5c309be776ac75422c769ce1ff549be

    env:
      NUXT_PUBLIC_DEFAULT_SERVER: "infosec.exchange"

    service:
      main:
        ports:
          http:
            port: 5314

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.hsn.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        hosts:
          - host: &host "elk.hsn.dev"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: elk-config

    resources:
      requests:
        cpu: 15m
        memory: 164M
      limits:
        memory: 1408M
