---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-config
  namespace: fediverse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
