---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr4k
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr4k-secret
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: sonarr
        property: api_key_4k
