---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr4k-config
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

  storageClassName: ceph-block
