---
clusterName: morgoth

talosVersion: v1.4.5
kubernetesVersion: 1.27.2
endpoint: "https://morgoth.jahanson.tech:6443"

cniConfig:
  name: none

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - morgoth.jahanson.tech

nodes:
  - hostname: galadriel.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.61
    controlPlane: true
    installDisk: /dev/sda
    nameserver: 10.1.1.1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: true
            addresses:
              - 10.1.1.61/24
  - hostname: elrond.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.62
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: true
            addresses:
              - 10.1.1.62/24
  - hostname: cirdan.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.63
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: true
            addresses:
              - 10.1.1.63/24
  - hostname: nenya.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.41
    controlPlane: false
    installDisk: /dev/sda
    nameserver: 10.1.1.1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: true
            addresses:
              - 10.1.1.41/24
          - vlanId: 40
            dhcp: false
            addresses:
              - 10.1.3.141/24
  - hostname: vilya.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.42
    controlPlane: false
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: true
            addresses:
              - 10.1.1.42/24
          - vlanId: 40
            dhcp: false
            addresses:
              - 10.1.3.142/24
  - hostname: narya.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.43
    controlPlane: false
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: true
            addresses:
              - 10.1.1.43/24
          - vlanId: 40
            dhcp: false
            addresses:
              - 10.1.3.144/24
controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnMasters: false
        proxy:
          disabled: true
        etcd:
          advertisedSubnets:
            - 10.1.1.0/24
        extraManifests:
          - https://raw.githubusercontent.com/jahanson/home-ops/main/infrastructure/talos/morgoth/integrations/kubelet-csr-approver/kubelet-csr-approver.yaml
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
        kubelet:
          extraArgs:
            feature-gates: CronJobTimeZone=true,GracefulNodeShutdown=true,NewVolumeManagerReconstruction=false
            rotate-server-certificates: "true"
          extraConfig:
            maxPods: 150
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - morgoth.jahanson.tech
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - 10.1.1.1
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
