---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-nenya
spec:
  restartPolicy: Never
  nodeName: nenya
  containers:
    - name: disk-wipe
      image: ghcr.io/onedr0p/alpine:3.18.0@sha256:dd504f02473c176a0e68e4550ccaf6f6c0f14e9f64c08a59877f9c6153bf48a9
      securityContext:
        privileged: true
      resources: {}
      env:
        - name: CEPH_DISK
          value: "/dev/nvme0n1"
      command:
        [
          "/bin/sh",
          "-c"
        ]
      args:
        - apk add --no-cache sgdisk util-linux parted;
          sgdisk --zap-all $CEPH_DISK;
          blkdiscard $CEPH_DISK;
          dd if=/dev/zero bs=1M count=10000 oflag=direct of=$CEPH_DISK;
          partprobe $CEPH_DISK;
          rm -rf /mnt/host_var/lib/rook
      volumeMounts:
        - mountPath: /mnt/host_var
          name: host-var
  volumes:
    - name: host-var
      hostPath:
        path: /var

---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-vilya
spec:
  restartPolicy: Never
  nodeName: vilya
  containers:
    - name: disk-wipe
      image: ghcr.io/onedr0p/alpine:3.18.0@sha256:dd504f02473c176a0e68e4550ccaf6f6c0f14e9f64c08a59877f9c6153bf48a9
      securityContext:
        privileged: true
      resources: {}
      env:
        - name: CEPH_DISK
          value: "/dev/nvme0n1"
      command:
        [
          "/bin/sh",
          "-c"
        ]
      args:
        - apk add --no-cache sgdisk util-linux parted;
          sgdisk --zap-all $CEPH_DISK;
          blkdiscard $CEPH_DISK;
          dd if=/dev/zero bs=1M count=10000 oflag=direct of=$CEPH_DISK;
          partprobe $CEPH_DISK;
          rm -rf /mnt/host_var/lib/rook
      volumeMounts:
        - mountPath: /mnt/host_var
          name: host-var
  volumes:
    - name: host-var
      hostPath:
        path: /var

---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-narya
spec:
  restartPolicy: Never
  nodeName: narya
  containers:
    - name: disk-wipe
      image: ghcr.io/onedr0p/alpine:3.18.0@sha256:dd504f02473c176a0e68e4550ccaf6f6c0f14e9f64c08a59877f9c6153bf48a9
      securityContext:
        privileged: true
      resources: {}
      env:
        - name: CEPH_DISK
          value: "/dev/nvme0n1"
      command:
        [
          "/bin/sh",
          "-c"
        ]
      args:
        - apk add --no-cache sgdisk util-linux parted;
          sgdisk --zap-all $CEPH_DISK;
          blkdiscard $CEPH_DISK;
          dd if=/dev/zero bs=1M count=10000 oflag=direct of=$CEPH_DISK;
          partprobe $CEPH_DISK;
          rm -rf /mnt/host_var/lib/rook
      volumeMounts:
        - mountPath: /mnt/host_var
          name: host-var
  volumes:
    - name: host-var
      hostPath:
        path: /var
