apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-gateway
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: "tailscale"
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:v1.42.0@sha256:f59fdba09b893af232c527b38c6016324f98aad14871628cffda147d02ca3112"
          env:
            - name: TS_KUBE_SECRET
              value: "tailscale-state"
            - name: TS_USERSPACE
              value: "false"
            - name: TS_ROUTES
              value: "10.244.0.0/16,10.1.1.0/24,10.96.0.0/12,10.45.0.0/16"
              # 10.244.0.0/16 pod cidr
              # 10.1.1.0/24 host cidr
              # 10.96.0.0/12 service cidr
              # 10.45.0.0/16 'external-ip' cidr
            - name: TS_EXTRA_ARGS
              value: "--advertise-exit-node --accept-routes"
          envFrom:
            - secretRef:
                name: tailscale-auth
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
