---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvidia-device-plugin
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: "./kubernetes/morgoth/apps/system/nvidia-device-plugin/app"
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 10m
  prune: true
  wait: true
