---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "hsn-dev"
  namespace: network
spec:
  secretName: "hsn-dev-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "hsn.dev"
  dnsNames:
    - "hsn.dev"
    - "*.hsn.dev"
