---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 17.10.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      enabled: false
      sentinel: false
    master:
      podLabels:
        role: master
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 34m
          memory: 93M
        limits:
          cpu: 155m
          memory: 415M
    replica:
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 34m
          memory: 93M
        limits:
          cpu: 155m
          memory: 415M
    sentinel:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        failureThreshold: 2
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 22m
          memory: 24M
        limits:
          cpu: 160m
          memory: 109M
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
      resources:
        requests:
          cpu: 10m
          memory: 24M
        limits:
          cpu: 105m
          memory: 109M
