---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 17.9.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      enabled: true
      sentinel: false
    master:
      podLabels:
        role: master
      persistence:
        enabled: false
    replica:
      persistence:
        enabled: false
    sentinel:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        failureThreshold: 2
      persistence:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
  valuesFrom:
    - kind: Secret
      name: redis-secret
      valuesKey: redis-password
      targetPath: auth.password