apiVersion: v1
kind: Pod
metadata:
  name: mastodon-tootctl
  namespace: fediverse
spec:
  containers:
    - name: mastodon-tootctl
      image: tootsuite/mastodon:latest
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      envFrom:
        - secretRef:
            name: mastodon-secret
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "500m"
          memory: "1Gi"