{
 "title": "Mastodon Stats",
 "description": "A comprehensive monitoring dashboard based on Mastodon's Prometheus statsd exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "puma_controller",
    "label": "Puma Controller",
    "query": {
     "query": "mastodon_controller_duration_count"
    }
   },
   {
    "name": "puma_action",
    "label": "Puma Action",
    "query": {
     "query": "mastodon_controller_duration_count"
    }
   },
   {
    "name": "puma_format",
    "label": "Puma Format",
    "query": {
     "query": "mastodon_controller_duration_count"
    }
   },
   { "name": "sql_table", "label": "SQL Table", "query": { "query": "mastodon_db_operation" } },
   { "name": "sql_operation", "label": "SQL Operation", "query": { "query": "mastodon_db_operation" } },
   { "name": "cache_operation", "label": "Cache Operation", "query": { "query": "mastodon_cache_duration_count" } },
   {
    "name": "sidekiq_worker",
    "label": "Sidekiq Worker",
    "query": {
     "query": "mastodon_sidekiq_worker_success_total"
    }
   }
  ]
 },
 "panels": [
  { "title": "Mastodon Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Puma QPS",
   "type": "stat",
   "description": "The total amount of HTTP Queries that Mastodon is serving.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by (mastodon)(rate(mastodon_controller_duration_count[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL ops/sec",
   "type": "stat",
   "description": "The total amount of SQL Queries that Mastodon is generating, split out in SELECT, DELETE, INSERT and UPDATE.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(mastodon_db_operation_count{operation=\"select\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (operation) (rate(mastodon_db_operation_count{operation=\"insert\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (operation) (rate(mastodon_db_operation_count{operation=\"update\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (operation) (rate(mastodon_db_operation_count{operation=\"delete\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL Latency",
   "type": "stat",
   "description": "The running average latency of SQL Queries that Mastodon is generating, split out in SELECT, DELETE, INSERT and UPDATE.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(mastodon_db_operation_sum{operation=\"select\"}[$__rate_interval])) /\nsum by (operation) (rate(mastodon_db_operation_count{operation=\"select\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (operation) (rate(mastodon_db_operation_sum{operation=\"insert\"}[$__rate_interval])) /\nsum by (operation) (rate(mastodon_db_operation_count{operation=\"insert\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (operation) (rate(mastodon_db_operation_sum{operation=\"update\"}[$__rate_interval])) /\nsum by (operation) (rate(mastodon_db_operation_count{operation=\"update\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (operation) (rate(mastodon_db_operation_sum{operation=\"delete\"}[$__rate_interval])) /\nsum by (operation) (rate(mastodon_db_operation_count{operation=\"delete\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache ops/sec",
   "type": "stat",
   "description": "The total amount of Cache Queries that Mastodon is generating.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by (operation)(rate(mastodon_cache_duration_count[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Latency",
   "type": "stat",
   "description": "The total amount of Cache Queries that Mastodon is generating.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by (operation) (rate(mastodon_cache_duration_sum[$__rate_interval])) /\nsum by (operation) (rate(mastodon_cache_duration_count[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq Jobs/sec",
   "type": "stat",
   "description": "The total amount of worker jobs that Sidekiq is performing.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by (mastodon)(rate(mastodon_sidekiq_worker_success_total[$__rate_interval])))",
     "legendFormat": "success"
    },
    {
     "expr": "sort(sum by (mastodon)(rate(mastodon_sidekiq_worker_failure_total[$__rate_interval])))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Sidekiq Queues",
   "type": "stat",
   "description": "The total amount of worker jobs that Sidekiq is performing.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by (mastodon)(mastodon_sidekiq_workers_size))",
     "legendFormat": "workers"
    },
    {
     "expr": "sort(sum by (mastodon)(mastodon_sidekiq_scheduled_size))",
     "legendFormat": "scheduled"
    },
    {
     "expr": "sort(sum by (mastodon)(mastodon_sidekiq_retry_size))",
     "legendFormat": "retry"
    },
    {
     "expr": "sort(sum by (mastodon)(mastodon_sidekiq_dead_size))",
     "legendFormat": "dead"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": {
    "content": "<img src='https://ipng.ch/assets/mastodon/mastodon-logo.svg' height='100%'>\n"
   }
  },
  {
   "title": "Puma Latency",
   "type": "stat",
   "description": "The running average latency of HTTP Queries that Mastodon is serving.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mastodon) (rate(mastodon_controller_duration_sum[$__rate_interval])) /\nsum by (mastodon) (rate(mastodon_controller_duration_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq Latency",
   "type": "stat",
   "description": "The running average latency of HTTP Queries that Mastodon is serving.",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mastodon) (rate(mastodon_sidekiq_worker_processing_time_sum[$__rate_interval])) /\nsum by (mastodon) (rate(mastodon_sidekiq_worker_processing_time_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Puma Controller Details ($puma_controller,$puma_action,$puma_format)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Operations ($puma_controller)",
     "type": "timeseries",
     "description": "Rate of queries/sec of API calls served by the Mastodon Webserver",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (controller) (rate(mastodon_controller_duration_count{controller=~\"$puma_controller\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Controller Return Codes ($puma_controller)",
     "type": "timeseries",
     "description": "Rate of response codes/sec of HTTP API calls served by the Mastodon Webserver",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "sum by (status) (rate(mastodon_controller_status{controller=~\"$puma_controller\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Controller Latency ($puma_controller)",
     "type": "timeseries",
     "description": "Current latency of API calls served by the Mastodon Webserver",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (controller) (rate(mastodon_controller_duration_sum{controller=~\"$puma_controller\"}[$__rate_interval])) /\nsum by (controller) (rate(mastodon_controller_duration_count{controller=~\"$puma_controller\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Action-Controller Operations ($puma_action)",
     "type": "timeseries",
     "description": "Rate of queries/sec of API calls served by the Mastodon Webserver, split out by action as well as controller.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum by (controller,action) (rate(mastodon_controller_duration_count{controller=~\"$puma_controller\",action=~\"$puma_action\"}[$__rate_interval]))",
       "legendFormat": "{{action}}-{{controller}}"
      }
     ]
    },
    {
     "title": "Action-Controller Return Codes ($puma_action,$puma_controller)",
     "type": "timeseries",
     "description": "Rate of response codes/sec of HTTP API calls served by the Mastodon Webserver",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "targets": [
      {
       "expr": "sum by (status) (rate(mastodon_controller_status{action=~\"$puma_action\",controller=~\"$puma_controller\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Action-Controller Latency ($puma_action)",
     "type": "timeseries",
     "description": "Current latency of API calls served by the Mastodon Webserver, split out by controller and action",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (controller,action) (rate(mastodon_controller_duration_sum{controller=~\"$puma_controller\",action=~\"$puma_action\"}[$__rate_interval])) /\nsum by (controller,action) (rate(mastodon_controller_duration_count{controller=~\"$puma_controller\",action=~\"$puma_action\"}[$__rate_interval]))",
       "legendFormat": "{{action}}-{{controller}}"
      }
     ]
    },
    {
     "title": "Action-Format-Controller Operations ($puma_action,$puma_format)",
     "type": "timeseries",
     "description": "Rate of queries/sec of API calls served by the Mastodon Webserver, split out by action, format and controller.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum by (controller,action,format) (rate(mastodon_controller_duration_count{controller=~\"$puma_controller\",action=~\"$puma_action\",format=~\"$puma_format\"}[$__rate_interval]))",
       "legendFormat": "{{action}}-{{format}}-{{controller}}"
      }
     ]
    },
    {
     "title": "Action-Format-Controller Return Codes ($puma_action,$puma_format,$puma_controller)",
     "type": "timeseries",
     "description": "Rate of response codes/sec of HTTP API calls served by the Mastodon Webserver",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "sum by (status) (rate(mastodon_controller_status{action=~\"$puma_action\",format=~\"$puma_format\",controller=~\"$puma_controller\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Action-Format-Controller Latency ($puma_action,$puma_format)",
     "type": "timeseries",
     "description": "Current latency of API calls served by the Mastodon Webserver, split out by controller and action",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (controller,action,format) (rate(mastodon_controller_duration_sum{controller=~\"$puma_controller\",action=~\"$puma_action\",format=~\"$puma_format\"}[$__rate_interval])) /\nsum by (controller,action,format) (rate(mastodon_controller_duration_count{controller=~\"$puma_controller\",action=~\"$puma_action\",format=~\"$puma_format\"}[$__rate_interval]))",
       "legendFormat": "{{action}}-{{format}}-{{controller}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Details ($sql_table,$sql_operation)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database SQL Operations",
     "type": "timeseries",
     "description": "Total amount of SQL operations across Mastodon - operations are SELECT, INSERT, DELETE and UPDATE.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (operation) (rate(mastodon_db_operation_count{operation=~\"$sql_operation\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Database SQL Latency",
     "type": "timeseries",
     "description": "Running latency of SQL operations across Mastodon - operations are SELECT, INSERT, DELETE and UPDATE.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (operation) (rate(mastodon_db_operation_sum{operation=~\"$sql_operation\"}[$__rate_interval])) / \nsum by (operation) (rate(mastodon_db_operation_count{operation=~\"$sql_operation\"}[$__rate_interval]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "90th ptile latency",
     "type": "gauge",
     "description": "The 90th percentile latency over all SELECT, INSERT, UPDATE and DELETE queries as seen by the client.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.9\",operation=\"select\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.9\",operation=\"insert\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.9\",operation=\"update\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.9\",operation=\"delete\"}>0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th ptile latency",
     "type": "gauge",
     "description": "The 99th percentile latency over all SELECT, INSERT, UPDATE and DELETE queries as seen by the client.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.99\",operation=\"select\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.99\",operation=\"insert\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.99\",operation=\"update\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.99\",operation=\"delete\"}>0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SQL Table Operations ($sql_table,$sql_operation)",
     "type": "timeseries",
     "description": "Lefthand graph is the number of SQL statements per second, split by table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(mastodon_db_operation_count{table=~\"$sql_table\",operation=~\"$sql_operation\"}[$__rate_interval])",
       "legendFormat": "{{table}}.{{operation}}"
      }
     ]
    },
    {
     "title": "SQL Table latency ($sql_table,$sql_operation)",
     "type": "timeseries",
     "description": "Lefthand graph is the latency of database operations specified by table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(mastodon_db_operation_sum{table=~\"$sql_table\",operation=~\"$sql_operation\"}[$__rate_interval]) / \nrate(mastodon_db_operation_count{table=~\"$sql_table\",operation=~\"$sql_operation\"}[$__rate_interval])",
       "legendFormat": "{{table}}.{{operation}}"
      }
     ]
    },
    {
     "title": "90th ptile latency ($sql_table)",
     "type": "gauge",
     "description": "The 90th percentile latency over SELECT, INSERT, UPDATE and DELETE queries to the specified SQL Table as seen by the client.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.9\",operation=\"select\",table=~\"$sql_table\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.9\",operation=\"insert\",table=~\"$sql_table\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.9\",operation=\"update\",table=~\"$sql_table\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.9\",operation=\"delete\",table=~\"$sql_table\"}>0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th ptile latency ($sql_table)",
     "type": "gauge",
     "description": "The 99th percentile latency over SELECT, INSERT, UPDATE and DELETE queries to the specified SQL Table as seen by the client.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.99\",operation=\"select\",table=~\"$sql_table\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.99\",operation=\"insert\",table=~\"$sql_table\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.99\",operation=\"update\",table=~\"$sql_table\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_db_operation{quantile=\"0.99\",operation=\"delete\",table=~\"$sql_table\"}>0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Details ($cache_operation)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Operations ($cache_operation)",
     "type": "timeseries",
     "description": "Cache operations per second from the Mastodon service",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by (operation)(rate(mastodon_cache_duration_count{operation=~\"$cache_operation\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache Latency ($cache_operation)",
     "type": "timeseries",
     "description": "Cache latency from the Mastodon service",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (operation)(rate(mastodon_cache_duration_sum{operation=~\"$cache_operation\"}[5m])) / \nsum by (operation)(rate(mastodon_cache_duration_count{operation=~\"$cache_operation\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "90th ptile latency",
     "type": "gauge",
     "description": "The 90th percentile latency over cache operations that are not hits as seen by the client.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (operation) (mastodon_cache_duration{quantile=\"0.9\",operation=\"read_miss\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_cache_duration{quantile=\"0.9\",operation=\"increment\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_cache_duration{quantile=\"0.9\",operation=\"write\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_cache_duration{quantile=\"0.9\",operation=\"generate\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_cache_duration{quantile=\"0.9\",operation=\"delete\"}>0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th ptile latency",
     "type": "gauge",
     "description": "The 99th percentile latency over cache operations that are not hits as seen by the client.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (operation) (mastodon_cache_duration{quantile=\"0.99\",operation=\"read_miss\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_cache_duration{quantile=\"0.99\",operation=\"increment\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_cache_duration{quantile=\"0.99\",operation=\"write\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_cache_duration{quantile=\"0.99\",operation=\"generate\"}>0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (operation) (mastodon_cache_duration{quantile=\"0.99\",operation=\"delete\"}>0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Sidekiq Details ($sidekiq_worker)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sidekiq Worker ($sidekiq_worker)",
     "type": "timeseries",
     "description": "Rate of sidekiq worker invocations by worker type, split out by success and failure.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by (worker)(rate(mastodon_sidekiq_worker_success_total{worker=~\"$sidekiq_worker\"}[$__rate_interval]))",
       "legendFormat": "{{worker}} Success"
      },
      {
       "expr": "sum by (worker)(rate(mastodon_sidekiq_worker_failure_total{worker=~\"$sidekiq_worker\"}[$__rate_interval]))",
       "legendFormat": "{{worker}} Failure"
      }
     ]
    },
    {
     "title": "Sidekiq Latency ($sidekiq_worker)",
     "type": "timeseries",
     "description": "Running latency of sidekiq worker invocations by worker type.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (worker)(rate(mastodon_sidekiq_worker_processing_time_sum{worker=~\"$sidekiq_worker\"}[$__rate_interval]))\n/ sum by (worker)(rate(mastodon_sidekiq_worker_processing_time_count{worker=~\"$sidekiq_worker\"}[$__rate_interval]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "50,90,99th ptile latency ($sidekiq_worker)",
     "type": "gauge",
     "description": "The median, 90th and 99th percentile latency over Sidekiq worker invocations.",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (quantile)(mastodon_sidekiq_worker_processing_time{quantile=\"0.5\",worker=~\"$sidekiq_worker\"}>0)",
       "legendFormat": "median"
      },
      {
       "expr": "avg by (quantile)(mastodon_sidekiq_worker_processing_time{quantile=\"0.9\",worker=~\"$sidekiq_worker\"}>0)",
       "legendFormat": "90th ptile"
      },
      {
       "expr": "avg by (quantile)(mastodon_sidekiq_worker_processing_time{quantile=\"0.99\",worker=~\"$sidekiq_worker\"}>0)",
       "legendFormat": "99th ptile"
      }
     ]
    },
    {
     "title": "Sidekiq Queue Depth",
     "type": "bargauge",
     "description": "A total number of worker jobs waiting in the queue, usually due to there not being enough worker threads or sidekiq jobs to handle them in time. This graph here shows the n-count of elements in the queue.",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort(sum by (queue)(mastodon_sidekiq_queue_enqueued))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sidekiq Queue Delay timeline",
     "type": "state-timeline",
     "description": "A historical graph of the average queue delay for each of the main queues in Sidekiq. If the queues do not have wait-time, they are depicted green. They will go through yellow, orange and become red once the queue is backing up and worker jobs have to wait before being scheduled.",
     "gridPos": { "h": 5, "w": 21, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(sum by (queue)(mastodon_sidekiq_queue_latency))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sidekiq Queue Delay",
     "type": "stat",
     "description": "The total amount of worker jobs that Sidekiq is performing.",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort(sum by (queue)(mastodon_sidekiq_queue_latency))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}