---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-trakt-sync
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: plex-trakt-sync-secret
    creationPolicy: Owner
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: Plex
        property: token_4k
    - secretKey: PLEX_USERNAME
      remoteRef:
        key: Plex
        property: plex_username
    - secretKey: TRAKT_USERNAME
      remoteRef:
        key: Plex
        property: trakt_username
