---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./sync-time.yaml
configMapGenerator:
  - name: sync-script-configmap
    files:
      - chrony-run.sh=./scripts/chrony-run.sh
generatorOptions:
  disableNameSuffixHash: true
