---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - angelnu.yaml
 - backube.yaml
 - bitnami.yaml
 - bjw-s.yaml
 - cilium.yaml
 - external-secrets.yaml
 - fairwinds.yaml
 - grafana.yaml
 - ingress-nginx.yaml
 - jetstack.yaml
 - kubernetes-sigs-descheduler.yaml
 - kubernetes-sigs-external-dns.yaml
 - kubernetes-sigs-metrics-server.yaml
 - kubernetes-sigs-nfd.yaml
 - kyverno.yaml
 - mastodon.yaml
 - nvidia-device-plugin.yaml
 - piraeus.yaml
 - postfinance.yaml
 - prometheus-community.yaml
 - rook-ceph.yaml
 - stakater.yaml
 - vector.yaml
 - weave-gitops.yaml
 - zalando-postgres-operator.yaml