---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - bitnami.yaml
 - bjw-s.yaml
 - cilium.yaml
 - external-secrets.yaml
 - fairwinds.yaml
 - grafana.yaml
 - ingress-nginx.yaml
 - jetstack.yaml
 - kubernetes-sigs-descheduler.yaml
 - kubernetes-sigs-metrics-server.yaml
 - piraeus.yaml
 - postfinance.yaml
 - prometheus-community.yaml
 - rook-ceph.yaml
 - stakater.yaml
 - vector.yaml