---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  namespace: media
spec:
  selector:
    matchLabels:
      app: photoprism
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: photoprism
    spec:
      containers:
        - name: photoprism
          image: docker.io/photoprism/photoprism:preview@sha256:b14c7cf1e187d0afd1f9aa6d12f48032a02bdd86071c83afad5430261109512e
          imagePullPolicy: IfNotPresent
          workingDir: /photoprism
          tty: true
          envFrom:
            - secretRef:
                name: photoprism-secret
          resources:
            requests:
              cpu: 100m
              nvidia.com/gpu: 1
              memory: 4282M
            limits:
              cpu: 2000m
              nvidia.com/gpu: 1
              memory: 12G
          ports:
            - name: http
              containerPort: 2342
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          volumeMounts:
            - name: photoprism-storage
              mountPath: /photoprism/storage
            - name: nfs-originals
              mountPath: /photoprism/originals
      volumes:
        - name: photoprism-storage
          persistentVolumeClaim:
            claimName: photoprism-storage
        - name: nfs-originals
          nfs:
            server: nas.jahanson.tech
            path: /volume1/Media/Photos
      runtimeClassName: nvidia
      nodeSelector:
        feature.node.kubernetes.io/pci-0300_10de.present: "true"
        modernnvidia: "true"
