---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: photoprism
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: photoprism-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PHOTOPRISM_ADMIN_USER: "{{ .photoprism_username }}"                 # admin login username
        PHOTOPRISM_ADMIN_PASSWORD: "{{ .photoprism_password }}"          # initial admin password (8-72 characters)
        PHOTOPRISM_AUTH_MODE: "password"               # authentication mode (public, password)
        PHOTOPRISM_SITE_URL: "https://photoprism.hsn.dev/"  # server URL in the format "http(s)://domain.name(:port)/(path)"
        PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
        PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
        PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, error, fatal, or panic
        PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
        PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
        PHOTOPRISM_DISABLE_CHOWN: "false"              # disables updating storage permissions via chmod and chown on startup
        PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
        PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
        PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
        PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
        PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
        PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW images
        PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW images (reduces performance)
        PHOTOPRISM_JPEG_QUALITY: 85                    # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
        PHOTOPRISM_DETECT_NSFW: "false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
        PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
        # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
        PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
        PHOTOPRISM_DATABASE_SERVER: "mariadb-photoprism.database.svc.cluster.local:3306"     # MariaDB or MySQL database server (hostname:port)
        PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
        PHOTOPRISM_DATABASE_USER: "{{ .mariadb_username }}"         # MariaDB or MySQL database user name
        PHOTOPRISM_DATABASE_PASSWORD: "{{ .mariadb_password }}"       # MariaDB or MySQL database user password
        PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
        PHOTOPRISM_SITE_DESCRIPTION: ""                # meta site description
        PHOTOPRISM_SITE_AUTHOR: ""                     # meta site author
        ## Run/install on first startup (options: update https gpu tensorflow davfs clitools clean):
        PHOTOPRISM_INIT: "tensorflow"
        ## Hardware Video Transcoding:
        PHOTOPRISM_FFMPEG_ENCODER: "nvidia"        # FFmpeg encoder ("software", "intel", "nvidia", "apple", "raspberry")
        # PHOTOPRISM_FFMPEG_BITRATE: "32"              # FFmpeg encoding bitrate limit in Mbit/s (default: 50)
        ## Run as a non-root user after initialization (supported: 0, 33, 50-99, 500-600, and 900-1200):
        # PHOTOPRISM_UID: 1000
        # PHOTOPRISM_GID: 1000
        # PHOTOPRISM_UMASK: 0000

  dataFrom:
    - extract:
        key: photoprism
      rewrite:
        - regexp:
            source: "(.*)"
            target: "photoprism_$1"
    - extract:
        key: mariadb-photoprism
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mariadb_$1"
