---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./deployment.yaml
  - ./externalsecret.yaml
  - ./ingress.yaml
  - ./service.yaml
  - ./volsync.yaml
commonLabels:
  app.kubernetes.io/name: photoprism
  app.kubernetes.io/instance: photoprism
