---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-storage
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: ceph-block
