---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: photoprism-restic
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: photoprism-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/photoprism'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: photoprism
  namespace: media
spec:
  sourcePVC: photoprism-storage
  trigger:
    schedule: "0 */12 * * *"
  restic:
    cacheCapacity: 3G
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: photoprism-restic-secret
    retain:
      daily: 14
