---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        FRIGATE_MQTT_USER: "{{ .mosquitto_frigate_username }}"
        FRIGATE_MQTT_PASSWORD: "{{ .mosquitto_frigate_password }}"
        FRIGATE_CAMERA_DRIVEWAY_HOST: driveway-camera.jahanson.tech
        FRIGATE_CAMERA_DRIVEWAY_USER: "{{ .driveway_username }}"
        FRIGATE_CAMERA_DRIVEWAY_PASSWORD: "{{ .driveway_password }}"
  dataFrom:
    - extract:
        key: mosquitto
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mosquitto_$1"
    - extract:
        key: Reolink 810A Driveway
      rewrite:
        - regexp:
            source: "(.*)"
            target: "driveway_$1"
