---
logger:
  default: info
  # logs:
  #   frigate.record: debug

birdseye:
  enabled: false

mqtt:
  host: 10.1.1.13
  port: 1883
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

# Global ffmpeg configuration
ffmpeg:
  hwaccel_args: preset-nvidia-h264

# Global snapshots configuration
snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 14

# Global record configuration
record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects

# Global objects configuration
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

# Specify camera's
go2rtc:
  streams:
    driveway_main:
      - rtsp://{FRIGATE_CAMERA_DRIVEWAY_USER}:{FRIGATE_CAMERA_DRIVEWAY_PASSWORD}@{FRIGATE_CAMERA_DRIVEWAY_HOST}:554/h264Preview_01_main
      - "ffmpeg:driveway_4k#audio=opus#video=h264"
    driveway_substream:
      - rtsp://{FRIGATE_CAMERA_DRIVEWAY_USER}:{FRIGATE_CAMERA_DRIVEWAY_PASSWORD}@{FRIGATE_CAMERA_DRIVEWAY_HOST}:554/h264Preview_01_sub
      - "ffmpeg:driveway#audio=opus"

cameras:
  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_4k?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: driveway_4k
    detect:
      width: 640
      height: 360
      fps: 15
    zones:
      front_yard_driveway:
        coordinates: 105,360,640,360,640,187,189,146,21,278
      front_yard_yard:
        coordinates: 605,195,190,145,423,8,593,7
      front_yard_street:
        coordinates: 0,287,142,178,384,22,378,0,232,1,0,101
    motion:
      mask:
        - 581,360,606,360,605,327,582,335
    objects:
      track:
        - person
        - car
        - bus