---
ansible_host: "10.1.1.11"
ansible_python_interpreter: /volume1/@appstore/python310/bin/python3

certificates:
  - common_name: "*.hsn.dev"
    email: "postmaster@veri.dev"
  - common_name: "*.jahanson.tech"
    email: "postmaster@veri.dev"

apps:
  syno_cli:
    # renovate: docker-image
    image: ghcr.io/reddec/syno-cli:0.1.2
    data_folder: /volume1/docker/syno_cli

  # autoscan:
  #   # renovate: docker-image
  #   image: cloudb0x/autoscan:1.3.0
  #   data_folder: /volume1/docker/autoscan

  minio:
    # renovate: docker-image
    image: quay.io/minio/minio:RELEASE.2023-04-20T17-56-55Z
    data_folder: /volume1/docker/minio/data

  node_exporter:
    # renovate: docker-image
    image: quay.io/prometheus/node-exporter:v1.5.0