---
clusterName: cluster-0

talosVersion: v1.3.6
kubernetesVersion: 1.26.1
endpoint: "https://cluster-0.jahanson.tech:6443"

cniConfig:
  name: none

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - cluster-0.jahanson.tech

nodes:
  - hostname: gandalf.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.31
    controlPlane: true
    installDisk: /dev/sdg
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 40
            dhcp: false
            addresses:
              - 10.1.3.141/24
  - hostname: glamdring.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.32
    controlPlane: true
    installDisk: /dev/nvme1n1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 40
            dhcp: false
            addresses:
              - 10.1.3.142/24
  - hostname: shadowfax.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.33
    controlPlane: true
    installDisk: /dev/nvme1n1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 40
            dhcp: false
            addresses:
              - 10.1.3.144/24
  - hostname: lembas.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.34
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 40
            dhcp: false
            addresses:
              - 10.1.3.143/24

controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnMasters: true
        apiServer:
        controllerManager:
        discovery:
          registries:
            service:
              disabled: true
        proxy:
          disabled: true
        scheduler:

      machine:
        files:
          - content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
            path: /etc/cri/conf.d/20-customization.part
            op: create
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true
            rotate-server-certificates: "true"
        install:
          extraKernelArgs:
            - "talos.logging.kernel=udp://vector.hsn.dev:6050/"
        logging:
          destinations:
            - endpoint: "udp://vector.hsn.dev:6051/"
              format: json_lines
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - cluster-0.jahanson.tech
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - 10.1.1.1

    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
