---
clusterName: cluster-0

talosVersion: v1.4.4
kubernetesVersion: 1.26.1
endpoint: "https://cluster-0.jahanson.tech:6443"

cniConfig:
  name: none

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - cluster-0.jahanson.tech

nodes:
  - hostname: nenya.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.41
    controlPlane: true
    installDisk: /dev/sda
    nameserver: 10.1.1.1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: true
            addresses:
              - 10.1.1.41/24
          - vlanId: 40
            dhcp: false
            addresses:
              - 10.1.3.141/24
  - hostname: vilya.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.42
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: true
            addresses:
              - 10.1.1.42/24
          - vlanId: 40
            dhcp: false
            addresses:
              - 10.1.3.142/24
  - hostname: narya.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.43
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: true
            addresses:
              - 10.1.1.43/24
          - vlanId: 40
            dhcp: false
            addresses:
              - 10.1.3.144/24
  - hostname: nahar.jahanson.tech
    disableSearchDomain: true
    ipAddress: 10.1.1.44
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: true
            addresses:
              - 10.1.1.44/24
          - vlanId: 40
            dhcp: false
            addresses:
              - 10.1.3.143/24

controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnMasters: true
        apiServer:
        controllerManager:
        discovery:
          registries:
            service:
              disabled: true
        proxy:
          disabled: true
        scheduler:

      machine:
        files:
          - content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
            path: /etc/cri/conf.d/20-customization.part
            op: create
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true
            rotate-server-certificates: "true"
        logging:
          destinations:
            - endpoint: "udp://vector.hsn.dev:6051/"
              format: json_lines
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - cluster-0.jahanson.tech
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: true

    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
