---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zalando-postgres-ui
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: postgres-operator-ui
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres-operator-ui
        namespace: flux-system
      interval: 5m
  # https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator-ui/values.yaml
  values:
    envs:
      # IMPORTANT: While operator chart and UI chart are independent, this is the interface between
      # UI and operator API. Insert the service name of the operator API here!
      # appUrl: "http://localhost:8081"
      operatorApiUrl: "http://postgres-operator:8080"
      operatorClusterNameLabel: "postgres"
      resourcesVisible: "True"
      targetNamespace: "database"
      teams:
        - "jahanson"

    resources:
      requests:
        cpu: 5m
        memory: 32M
      limits:
        memory: 100M