---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-tunnel
  namespace: network
  annotations:
    external-dns.alpha.kubernetes.io/target: ingress.hsn.dev
spec:
  endpoints:
    - dnsName: ingress.hsn.dev
      recordType: CNAME
      targets: ["a38b545f-c568-4b6e-9b9e-11ac913684e4.cfargotunnel.com"]
