---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.13.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: flux-system
  values:
    name: nvidia-device-plugin
    runtimeClassName: nvidia
    # Node Selector for the DaemonSet
    nodeSelector:
      feature.node.kubernetes.io/pci-0300_10de.present: "true"