---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: nvdp-configmap
    files:
      - config/nvidia.yaml
generatorOptions:
  disableNameSuffixHash: true