---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./chrony-sync/ks.yaml
  - ./descheduler/ks.yaml
  - ./nvidia-device-plugin/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./reloader/ks.yaml
  - ./volsync/ks.yaml
